# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Reazon Research'
copyright = '2022, Human Interaction Laboratory'
author = 'Human Interaction Laboratory'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
    "sphinxcontrib.googleanalytics",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
locale_dirs = ['locale/']
language = 'ja'

gettext_compact = False
add_module_names = False

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

googleanalytics_id = 'G-S1KMDX1V1H'
googleanalytics_enabled = True

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
root_doc = 'index'
html_theme = 'reazon_theme'
html_title = 'Reazon Human Interaction Lab'
html_baseurl = 'https://research.reazon.jp'
# html_css_files = ['custom.css']
html_copy_source = False

html_theme_options = {
    # "sidebar_hide_name": True,
    # "source_repository": "https://github.com/reazon-research/reazon-research.github.io/",
    # "source_branch": "main",
    # "source_directory": "source/",
    "light_logo": "logo.png",
    "dark_logo": "logo-dark.png",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_context = {
    'support_languages': {
        'ja': 'JP',
        'en': 'EN'
    }
}
